version: '3'

services:
  backend:
    env_file:
      - backend/.env
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - "3002:3002"

  frontend:
    build: frontend
    entrypoint: [ "nginx", "-g", "daemon off;" ]
    volumes:
      - ./frontend:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3002
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  node-modules: